# These are supported funding model platforms

github: [miaowing]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: miaowing
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://sponsor.zf.ink
